### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by rogiermars** [armouroflight/gstreamer1.x-java#1]
He just a quick question.

Are you continue this project? If so maybe we can give you a helping hand!

Greetings,

Roger

**Comment by codeanticode** [comment]
@rogiermars seems that this repo is no longer active. I just created a fork in the [gstreamer-org](https://github.com/gstreamer-java) org, where we are trying to aggregate all the development efforts. You help offer is still welcome!

**Comment by armouroflight** [comment]
Sorry I should have put more time into this, but it's been working as far as I needed it to and I haven't had any good ideas of what to do next.

If you can make something of this then that's great, I hope it's helpful to people.

**Comment by codeanticode** [comment]
@armouroflight: thanks a lot for all this work, and the recent updates! We have created a github org called [gstreamer-java](https://github.com/gstreamer-java) to try to centralize all the development efforts. Right now, we have three repos in the org:
- [gstreamer-java](https://github.com/gstreamer-java/gstreamer-java) The original 0.10 bindings.
- [gstreamer1.x-java](https://github.com/gstreamer-java/gstreamer1.x-java) A fork of this repo. I was able to use it to update the video library in [Processing](https://processing.org/) to gstreamer 1.x.
- [gir2java](https://github.com/gstreamer-java/gir2java) A project that was developed as part of Google Summer of Code last year, where the goal is to automatically generate the bindings for gstreamer 1.x using the gir files.

gir2java is the most forward looking approach, since once it works we should be able to easily update the bindings to accommodate any changes in the gstreamer API. It is currently half way there: you can run a simple pipeline from Java with it, but there are several missing pieces of functionality, and it needs a higher level API, since it right now simply generates classes that wrap the underlying gst object very closely.

In order to have a working version of the 1.x bindings until gir2java is completed, perhaps we can use yours with some additional patches and fixes, as I mentioned I was able to run gstreamer 1.x in Processing's video library using gstreamer-1.x-java. One important thing that was missing was support for capture devices, in particular the device query API changed completely in 1.x, so this would need some more work. This is something I could try to do, so I'm wondering if you would be able to help me with that. Also, are you interested in becoming a member of the gstreamer-java organization?
